baseURL = "https://hkpeterpeter.github.io/"
languageCode = "en-us"
title = "Peter's website"

[params]
author = "Peter Chung"
keywords = "Hackathon, hackUST, Hackathon@HKUST, Datathon, Alumni, HKUST, CSE, Entrepreneur, Startup, Cyberport, SIGHT, TA, cspeter, Peter"







