baseURL = "https://hkpeterpeter.github.io/"
languageCode = "en-us"
title = "Peter's website"
disqusShortname = "peters-website"  # disqus setting
googleAnalytics = "UA-115752671-1"  # GA setting
paginate = 3  # Define the number of posts per page

[params]
author = "Peter Chung"
keywords = "Hackathon, hackUST, Hackathon@HKUST, Datathon, Alumni, HKUST, CSE, Entrepreneur, Startup, Cyberport, SIGHT, TA, cspeter, Peter"








