slideshow = [
    {
        "title" : "Received HKUST SENtastic Staff Award 2025",
        "url"   : "slideshow/hkust_sentastic_award_2025.jpg",
        "tags"  : ["Teaching", "SEN", "Advising"]
    },

{
"title" : "Finalist, AMC AI Film Festival 2025 at HKUST",
"url" : "slideshow/AMC_File_Festival_2025.webp",
"tags" : ["Generative AI", "Teaching"],
},

{
"title" : "Animating My AI Generated Robotic Cat using Kling AI",
"url" : "slideshow/gen_ai_cat_2024.webp",
"tags" : ["Generative AI"],
},

{
"title" : "CSE Graduation Dinner 2024",
"url" : "slideshow/CSE_Grad_Dinner_2024.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "EMIA2020 Design Thinking Course Guest Lecture 2023",
"url" : "slideshow/EMIA2020_Design_Thinking_Guest_Lecture_2023.png",
"tags" : ["Teaching", "Generative AI"],
},

{
"title" : "CSE Graduation Dinner 2023",
"url" : "slideshow/CSE_Grad_Dinner_2023.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "A birthday card to my cat, generated by different AI tools, 2023",
"url" : "slideshow/gugucat_birthday_card_2023.png",
"tags" : ["Art", "Generative AI"],
},

{
"title" : "Teaching Awards at Department of CSE, HKUST, 2021",
"url" : "slideshow/teaching_awards_cse_2021.png",
"tags" : ["Teaching"],
},

{
"title" : "A gift from HKUST Alumni Office 2020",
"url" : "slideshow/gift_from_alumni_office_2020.jpg",
"tags" : ["Alumni"],
},

{
"title" : "SmarTone Hackathon 2019",
"subtitle" : "Theme: 5G and Smart City",
"url" : "slideshow/smartone_hackathon_2019.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "SENG Chatbot Workshop 2019",
"subtitle" : "for high school STEM education",
"url" : "slideshow/chatbot_workshop_2019.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSE Farewell Dinner 2019",
"url" : "slideshow/CSE_Farewell_Dinner_2019.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "hackUST 2019",
"url" : "slideshow/hackUST_2019.jpg",
"tags" : ["Hackathon", "Entrepreneurship", "Alumni", "Teaching"],
},

{
"title" : "Data and Media Hackathon 2019",
"url" : "slideshow/data_media_hack_2019.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "CSEAA Coffee Appreciation Workshop 2018",
"url" : "slideshow/cseaa_coffee_appreciation_workshop_2018.jpg",
"tags" : ["Alumni"],
},

{
"title" : "CSAA Connects the World Annual Gathering 2018",
"url" : "slideshow/CSAA_connects_the_world_annual_gathering_2018.jpg",
"tags" : ["Alumni", "Entrepreneurship"],
},

{
"title" : "Inter-School Innovation Competition on Insurance Technology 2018",
"url" : "slideshow/insurtech_challenge_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "HKUST Alumni Reunion Day 2018",
"url" : "slideshow/HKUST_Alumni_Reunion_2018.jpg",
"tags" : ["Alumni"],
},

{
"title" : "Facebook Chatbot Workshop for Alumni Families 2018",
"url" : "slideshow/chatbot_workshop_alumni_families_2018.jpg",
"tags" : ["Alumni", "Teaching"],
},

{
"title" : "AIA Life Hackathon 2018",
"url" : "slideshow/aialifehack_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Smart City Hong Kong Hackathon 2018",
"url" : "slideshow/smartcity_hackathon_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "HKUST Engineering Alumni Day Shenzhen 2018",
"url" : "slideshow/HKUST_Engineering_Alumni_Day_Shenzhen_2018.jpg",
"tags" : ["Alumni"],
},

{
"title" : "Entrepreneur First Hong Kong (Cohort 1) - Kick-off Day",
"url" : "slideshow/efhk1_kod_2018.jpg",
"tags" : ["Entrepreneurship"],
},

{
"title" : "AngelHack Hong Kong 2018",
"url" : "slideshow/ah_hk_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "CSAA Connects the World Dinner 2018",
"url" : "slideshow/csaa_connects_the_world_2018.jpg",
"tags" : ["Alumni", "Entrepreneurship"],
},

{
"title" : "PolyU x Radica Big Datathon 2018",
"url" : "slideshow/polyu_radica_bigdatathon_2018.jpg",
"tags" : ["Hackathon", "Alumni", "Teaching", "Entrepreneurship"],
},

{
"title" : "CSE Graduation Dinner 2018",
"url" : "slideshow/CSE_Grad_Dinner_2018.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "hackUST 2018",
"url" : "slideshow/hackUST_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Access to Justice InnoTech Law Hackathon 2018",
"url" : "slideshow/a2j_innotech_hackathon_2018.jpg",
"tags" : ["Hackathon"],
"subtitle" : "Won the second runner-up in Justus team",
},

{
"title" : "Cyberport Startup Weekend FinTech Hong Kong 2018",
"url" : "slideshow/startupweekend_fintech_2018.jpg",
"tags" : ["Alumni","Entrepreneurship"],
"subtitle" : "Supported the event as an executive committee member of Cyberport Startup Alumni Association",
},

{
"title" : "Cyberport Alumni New Year Networking Lunch 2018",
"url" : "slideshow/Cyberport Alumni_Lunar_New_Year_Networking_Lunch_2018.jpg",
"tags" : ["Alumni", "Entrepreneurship"],
},

{
"title" : "Global Legal Hackathon Hong Kong 2018",
"subtitle" : "Won the second runner-up in Legot team",
"url" : "slideshow/global_legal_hackathon_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Fishackathon Hong Kong 2018",
"subtitle" : "Part of the organizing committee",
"url" : "slideshow/fishackathon_hk_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "AS Watson Hackathon 2018",
"url" : "slideshow/aswatson_hackathon_2018.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Cyberport Startup Graduation Ceremony 2017",
"url" : "slideshow/habhub_ccmf_grad.jpg",
"tags" : ["Entrepreneurship", "Alumni"],
},

{
"title" : "HKUSTxRadica Big Datathon 2017",
"url" : "slideshow/hkust_radica_bigdatathon_2017.jpg",
"tags" : ["Hackathon","Alumni"],
"subtitle" : "Co-organized by Radica and BDI, HKUST",
},

{
"title" : "SmarTone Hackathon 2017",
"url" : "slideshow/smartonehackathon_2017.jpg",
"tags" : ["Hackathon"],
"subtitle" : "Served as AngelHack Hong Kong Ambassador",
},

{
"title" : "CSAA Mid-Autumn Festival Party and ExCo meeting 2017",
"url" : "slideshow/CSAA_mid_autumn_exco_meeting_2017.jpg",
"tags" : ["Alumni","Entrepreneurship"],
},

{
"title" : "HKUST Alumni Visit 2017",
"subtitle" : "Shenzhen BlueBay Incubation Program",
"url" : "slideshow/alumni_visit_hkust_bluebay_incubation_2017.jpg",
"tags" : ["Alumni","Entrepreneurship"],
},

{
"title" : "Social-up Youth Program 2017",
"subtitle" : "Served as Judge of the pitching competition",
"url" : "slideshow/SoInSoGood_HKSTP_2017.jpg",
"tags" : ["Entrepreneurship"],
},

{
"title" : "SENG Alumni Social Mixer 2017",
"url" : "slideshow/SENG_Alumni_Social_Mixer_2017.jpg",
"tags" : ["Alumni"],
},

{
"title" : "RISE Conference Hong Kong 2017",
"subtitle" : "Being interviewed by TVB about HabHub",
"url" : "slideshow/HabHub_TVB_Interview_RISE.jpg",
"tags" : ["Entrepreneurship"],
},

{
"title" : "SENG Facebook Chatbot Workshop",
"subtitle" : "for high school STEM education",
"url" : "slideshow/SENG_Facebook_Chatbot_Workshop.jpg",
"tags" : ["Teaching"],
},

{
"title" : "Cyberport Startup Alumni Association Dinner 2017",
"url" : "slideshow/CSAA_connects_the_world_dinner_2017.jpg",
"tags" : ["Entrepreneurship", "Alumni" ],
},

{
"title" : "Open Source Hong Kong Conference 2017",
"url" : "slideshow/oshk_conf_2017.jpg",
"tags" : ["Teaching"],
},

{
"title" : 'AngelHack Hong Kong 2017',
"url" : "slideshow/angelhack_hongkong_2017.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Hang Seng FinTech Hackathon 2017",
"url" : "slideshow/hs_hackathon_2017.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "Cyberport Alumni Association Ice-break meetup 2017",
"url" : "slideshow/Cyberport_Alumni_Association_2017.jpg",
"tags" : ["Alumni", "Entrepreneurship"],
},

{
"title" : "CSE Farewell Dinner 2017",
"url" : "slideshow/CSE_Farewell_Dinner_2017.jpg",
"tags" : ["Teaching"],
},

{
"title" : "hackUST 2017",
"url" : "slideshow/hackUST_2017.png",
"tags" : ["Hackathon"],
},

{
"title" : "SuperCharger 2.0 FinTech Hackathon 2017",
"url" : "slideshow/supercharger_fintech_hackathon_2017.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "SENG Shenzhen Alumni Gathering 2017",
"url" : "slideshow/SENG_Engineering_Alumni_Gathering_2017.jpg",
"tags" : ["Alumni"],
},

{
"title" : "Microsoft ImagineHack 2017",
"url" : "slideshow/Microsoft_ImagineHack_2017.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "HealthTech Asia 2017",
"url" : "slideshow/habhub-health-tech-asia-2017.jpg",
"tags" : ["Entrepreneurship"],
},

{
"title" : "Hour of Code Hong Kong 2nd anniversary",
"url" : "slideshow/HoC-2nd-anniversary-HabHub-Booth.jpg",
"tags" : ["Entrepreneurship"],
},

{
"title" : "CSEAA LightHouse of IT Trends Event 2016/17",
"url" : "slideshow/CSEAA_Lighthouse_Of_IT_Trends_2016.jpg",
"tags" : ["Alumni"],
},

{
"title" : "Hack-O-Life 2016",
"url" : "slideshow/hack-of-life-2016.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "JeJu Hackathon 2016, South Korea",
"url" : "slideshow/JeJu_Hackathon_2016_Blogory.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "hackJam 2016",
"url" : "slideshow/hackJam_2016.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "CSESS Photo Taking 2016",
"url" : "slideshow/CSESS_PhotoTaking_2016.jpg",
"tags" : ["Teaching"],
},

{
"title" : "HKUST Alumni Homecoming Workshop 2016",
"url" : "slideshow/HKUST_Alumni_Homecoming_Workshop_2016.jpg",
"tags" : ["Alumni"],
},

{
"title" : "HKU Dreamcatcher Hackathon 2016",
"url" : "slideshow/HKU_Dreamcatcher_Hackathon_2016.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "HKUST SENG Alumni Fun Day 2016",
"url" : "slideshow/SENG_Alumni_Fun_Day_2016.jpg",
"tags" : ["Alumni"],
},

{
"title" : "HKUST A1 Entrepreneurship Night 2016",
"url" : "slideshow/A1_Entrepreneurship_Night_2016.jpg",
"tags" : ["Entrepreneurship", "Alumni"],
},

{
"title" : "HKUST 25th Anniversary Exhibition",
"url" : "slideshow/HKUST_25A_Exhibition.jpg",
"tags" : ["Teaching", "Hackathon"],
},

{
"title" : "hackUST 2016",
"url" : "slideshow/hackUST_2016.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "HKUST Alumni Association A1 Startup Award Ceremony 2016",
"url" : "slideshow/HKUST_A1_Startup_Award_Ceremony_2016.jpg",
"tags" : ["Alumni"],
},

{
"title" : "SENG Engineering Alumni Gathering 2015 in Shenzhen",
"url" : "slideshow/SENG_Engineering_Alumni_Gathering_2015.jpg",
"tags" : ["Alumni"],
},

{
"title" : "CSE Alumni Homecoming Day 2015",
"url" : "slideshow/CSE_alumni_homecoming_day_2015.jpg",
"tags" : ["Alumni"],
},

{
"title" : "Hour of Code@HKUST 2015",
"url" : "slideshow/HOC_for_alumni_families_2015.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "SIGHT Camp Closing Ceremony 2015",
"url" : "slideshow/SIGHT_Camp_Closing_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Photo Taking 2015",
"url" : "slideshow/CSESS_PhotoTaking_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "SIGHT MIT AppInventor 2 Workshop 2015",
"url" : "slideshow/SIGHT_MIT_AppInventor2_workshop_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "Mooncakes from Tencent Charity Foundation",
"url" : "slideshow/hackUST_Tencent_Mooncakes.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "SIGHT Cambodia Trip 2015",
"url" : "slideshow/SIGHT_cambodia_trip_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Farewell Dinner 2015",
"url" : "slideshow/CSESS_Farewell_Dinner_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "hackUST 2015 Media Briefing",
"url" : "slideshow/Hackathon_Media_Briefing_2015.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "SIGHT High School Workshop 2015",
"url" : "slideshow/SIGHT_workshop_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "SENG Alumni Family Fun Day 2015",
"url" : "slideshow/SENG_Alumni_Family_Funday_2015.jpg",
"tags" : ["Alumni"],
},

{
"title" : "hackUST 2015",
"url" : "slideshow/Hackathon_2015.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "CSEAA Mentorship Program Kick-off Meeting 2015",
"url" : "slideshow/CSEAA_Mentorship_Kickoff_2015.jpg",
"tags" : ["Alumni"],
},

{
"title" : "CSESS Open Semester Party 2015",
"url" : "slideshow/CSESS_OpenSem_Gathering_2015.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Annual Dinner 2014",
"url" : "slideshow/CSESS_Annual_Dinner_2014.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSE Alumni Gathering and Dinner 2014",
"url" : "slideshow/CSEAA_Annual_Gathering_2014.jpg",
"tags" : ["Alumni"],
},

{
"title" : "CSESS Photo Taking Day 2014",
"url" : "slideshow/CSESS_PhotoTaking_2014.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Farewell HighTable Dinner 2014",
"url" : "slideshow/CSESS_Farewell_HighTable_Dinner_2014.jpg",
"tags" : ["Teaching"],
},

{
"title" : "hackUST 2014",
"url" : "slideshow/EClub_Hackathon_2014.jpg",
"tags" : ["Hackathon"],
},

{
"title" : "CSEAA Mentorship Program Kick-off Meeting 2014",
"url" : "slideshow/CSEAA_Mentorship_Kickoff_2014.jpg",
"tags" : ["Teaching", "Alumni"],
},

{
"title" : "CSESS Open Semester Party 2014",
"url" : "slideshow/CSESS_OpenSem_Party_2014.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Annual Dinner 2013",
"url" : "slideshow/CSESS_Annual_Dinner_2013.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSE Alumni Gathering and Dinner 2013",
"url" : "slideshow/CSEAA_Annual_Gathering_2013_big.jpg",
"tags" : ["Alumni"],
},

{
"title" : "CSESS Photo Taking Day 2013",
"url" : "slideshow/CSESS_PhotoTaking_2013.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Farewell HighTable Dinner 2012",
"url" : "slideshow/CSESS_Farewell_HighTable_Dinner_2012_big.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Annual Dinner 2011",
"url" : "slideshow/CSESS_Annual_Dinner_2011_big.jpg",
"tags" : ["Teaching"],
},

{
"title" : "CSESS Annual Dinner 2010",
"url" : "slideshow/CSESS_Annual_Dinner_2010_big.jpg",
"tags" : ["Teaching"],
},

]